name: CI Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - '*'
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/ci.yml"
      - ".golangci.yml"

jobs:
  lint:
    permissions:
      contents: read
    uses: jsandas/github-actions/.github/workflows/golang-lint.yml@main

  security:
    permissions:
      contents: read
      security-events: write
    uses: jsandas/github-actions/.github/workflows/golang-security.yml@main

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
        cache: true

    - name: Run unit tests
      run: go test -v ./...
